#define OPJ_HAVE_INTTYPES_H 	1
#define OPJ_PACKAGE_VERSION "2.5.0"
#define OPJ_HAVE_MALLOC_H

#if defined(WIN32)
#define OPJ_HAVE__ALIGNED_MALLOC
#endif

#if defined(UNIX)
#define OPJ_HAVE_MEMALIGN
#define OPJ_HAVE_POSIX_MEMALIGN
#define _POSIX_C_SOURCE 200112L
#endif

#if defined(APPLE)
#define OPJ_HAVE_MEMALIGN
#define OPJ_HAVE_POSIX_MEMALIGN
#define _POSIX_C_SOURCE 200112L
#define OPJ_BIG_ENDIAN
#endif
